# Generated by Django 5.1.6 on 2025-04-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_event_is_group_wide_event_specific_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_open_store',
            field=models.BooleanField(default=False),
        ),
    ]
