# Generated by Django 5.1.6 on 2025-04-08 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0004_event_is_open_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_open_store',
        ),
    ]
